version: '3.4'

networks:
  default:
    external:
      name: nat
services:
  domain:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_EventStoreConnection=${EVENTSTORE_SERVER:-eventstore}
      - ESHOP_EventStoreUserName=${EVENTSTORE_USERNAME}
      - ESHOP_EventStorePassword=${EVENTSTORE_PASSWORD}
      - ESHOP_SeqConnection=${SEQ_SERVER:-http://seq:5341}
  mongo:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_EventStoreConnection=${EVENTSTORE_SERVER:-eventstore}
      - ESHOP_EventStoreUserName=${EVENTSTORE_USERNAME}
      - ESHOP_EventStorePassword=${EVENTSTORE_PASSWORD}
      - ESHOP_MongoDbConnection=${MONGODB_SERVER:-mongodb://mongodb:27017}
      - ESHOP_SeqConnection=${SEQ_SERVER:-http://seq:5341}
  elastic:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_EventStoreConnection=${EVENTSTORE_SERVER:-eventstore}
      - ESHOP_EventStoreUserName=${EVENTSTORE_USERNAME}
      - ESHOP_EventStorePassword=${EVENTSTORE_PASSWORD}
      - ESHOP_ElasticConnection=${ELASTIC_SERVER:-http://elasticdb:9200}
      - ESHOP_ElasticUserName=${EVENTSTORE_USERNAME}
      - ESHOP_ElasticPassword=${EVENTSTORE_PASSWORD}
      - ESHOP_SeqConnection=${SEQ_SERVER:-http://seq:5341}
  presentation:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_ServiceStackLicense=${SERVICESTACK_LICENSE}
      - ESHOP_SeqConnection=${SEQ_SERVER:-http://seq:5341}
  #frontend:
  #  build:
  #    args:
  #      API_SERVER: http://localhost:8080
