version: '3.4'

services:
  domain:
    image: eshop/domain:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Endpoints/Domain/Dockerfile
    depends_on:
      - rabbitmq
      - seq
      - eventstore
    restart: always
  mongo:
    image: eshop/mongodb:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Endpoints/MongoDb/Dockerfile
    depends_on:
      - rabbitmq
      - seq
      - eventstore
      - mongodb
    restart: always
  elastic:
    image: eshop/elastic:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Endpoints/Elastic/Dockerfile
    depends_on:
      - rabbitmq
      - seq
      - eventstore
      - elasticdb
    restart: always
  presentation:
    image: eshop/presentation:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Endpoints/Presentation/Dockerfile
    depends_on:
      - rabbitmq
      - seq
    ports:
      - "8080:80"
    restart: always
  #frontend:
  #  image: eshop/frontend:${TAG:-latest}
  #  build:
  #    context: .
  #    dockerfile: src/Web/Dockerfile
  #  depends_on:
  #    - presentation
  #  ports:
  #    - "80:80"

  # windows image
  #rabbitmq:
  #  image: spring2/rabbitmq
  #  ports:
  #    - "15672:15672"
  #    - "5672:5672"

  # linux images
  elastichq:
    image: elastichq/elasticsearch-hq
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
  eventstore:
    image: eventstore/eventstore
    ports:
      - "1113:1113"
      - "2113:2113"
    restart: always
  mongodb:
    image: mongo:3.7-jessie
    ports:
      - "27017:27017"
    restart: always
  elasticdb:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    environment:
      - cluster.name=eshop
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - transport.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    restart: always
  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "15341:80"
