version: '3.7'

networks:
  default:
    name: nat
services:
  domain:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_EventStoreConnection=${EVENTSTORE_SERVER:-eventstore}
      - ESHOP_EventStoreUserName=${EVENTSTORE_USERNAME}
      - ESHOP_EventStorePassword=${EVENTSTORE_PASSWORD}
  mongo:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_EventStoreConnection=${EVENTSTORE_SERVER:-eventstore}
      - ESHOP_EventStoreUserName=${EVENTSTORE_USERNAME}
      - ESHOP_EventStorePassword=${EVENTSTORE_PASSWORD}
      - ESHOP_MongoDbConnection=${MONGODB_SERVER:-mongodb://mongodb:27017}
  elastic:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_EventStoreConnection=${EVENTSTORE_SERVER:-eventstore}
      - ESHOP_EventStoreUserName=${EVENTSTORE_USERNAME}
      - ESHOP_EventStorePassword=${EVENTSTORE_PASSWORD}
      - ESHOP_ElasticConnection=${ELASTIC_SERVER:-http://elasticdb:9200}
      - ESHOP_ElasticUserName=${EVENTSTORE_USERNAME}
      - ESHOP_ElasticPassword=${EVENTSTORE_PASSWORD}
  presentation:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_ServiceStackLicense=${SERVICESTACK_LICENSE}
      - ESHOP_HostServer=http://${HOST_SERVER:-localhost}
