version: '3.4'

networks:
  default:
    external:
      name: nat
services:
  domain:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_EventStoreConnection=${EVENTSTORE_SERVER:-eventstore}
      - ESHOP_EventStoreUserName=${EVENTSTORE_USERNAME}
      - ESHOP_EventStorePassword=${EVENTSTORE_PASSWORD}
  mongodb:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_EventStoreConnection=${EVENTSTORE_SERVER:-eventstore}
      - ESHOP_EventStoreUserName=${EVENTSTORE_USERNAME}
      - ESHOP_EventStorePassword=${EVENTSTORE_PASSWORD}
      - ESHOP_MongoDbConnection=${MONGODB_SERVER:-mongo}
  elastic:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
      - ESHOP_EventStoreConnection=${EVENTSTORE_SERVER:-eventstore}
      - ESHOP_EventStoreUserName=${EVENTSTORE_USERNAME}
      - ESHOP_EventStorePassword=${EVENTSTORE_PASSWORD}
      - ESHOP_ElasticConnection=${ELASTIC_SERVER:-elastic}
  servicestack:
    environment:
      - ESHOP_RabbitConnection=${RABBIT_SERVER:-rabbitmq}
      - ESHOP_RabbitUserName=${RABBIT_USERNAME}
      - ESHOP_RabbitPassword=${RABBIT_PASSWORD}
  frontend:
    build:
      args:
        API_SERVER: http://localhost:8080
